/*
 * Copyright (C) 1994-2020 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of both the OpenPBS software ("OpenPBS")
 * and the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * OpenPBS is free software. You can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * OpenPBS is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * PBS Pro is commercially licensed software that shares a common core with
 * the OpenPBS software.  For a copy of the commercial license terms and
 * conditions, go to: (http://www.pbspro.com/agreement.html) or contact the
 * Altair Legal Department.
 *
 * Altair's dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of OpenPBS and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair's trademarks, including but not limited to "PBS™",
 * "OpenPBS®", "PBS Professional®", and "PBS Pro™" and Altair's logos is
 * subject to Altair's trademark licensing policies.
 */

#include <pbs_config.h>   /* the master config generated by configure */

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "pbs_ifl.h"
#include "base_obj.h"
#include "libpbs.h"
#include "attribute.h"
#include "job.h"
#include "pbs_error.h"
#include "pbs_nodes.h"

void
__reset_attr_flag(void *pobj, int attr_idx, int flag, obj_type_t obj_type)
{
	if (!pobj)
		return;

	switch (obj_type) {
	case OBJ_JOB:
		((job *)pobj)->ji_wattr[attr_idx].at_flags = flag;
		break;
#ifndef PBSMOM
	case OBJ_NODE:
		((pbs_node *)pobj)->nd_attr[attr_idx].at_flags = flag;
		break;
#endif
	default:
		break;
	}
}

void
__set_attr_flag(void *pobj, int attr_idx, int flag, obj_type_t obj_type)
{
        if (!pobj)
		return;

	switch (obj_type) {
	case OBJ_JOB:
		((job *)pobj)->ji_wattr[attr_idx].at_flags |= flag;
		break;
#ifndef PBSMOM
	case OBJ_NODE:
		((pbs_node *)pobj)->nd_attr[attr_idx].at_flags |= flag;
		break;
#endif

	default:
		break;
	}
}

void
__unset_attr_flag(void *pobj, int attr_idx, int flag, obj_type_t obj_type)
{
        if (!pobj)
		return;

	switch (obj_type) {
	case OBJ_JOB:
		((job *)pobj)->ji_wattr[attr_idx].at_flags &= ~flag;
		break;
#ifndef PBS_MOM
	case OBJ_NODE:
		((pbs_node *)pobj)->nd_attr[attr_idx].at_flags &= ~flag;
		break;
#endif

	default:
		break;
	}
}

int
__is_attr_flag_set(const void *pobj, int attr_idx, int flag, obj_type_t obj_type)
{
        if (!pobj)
		return 0;

	switch (obj_type) {
	case OBJ_JOB:
                return ((job *)pobj)->ji_wattr[attr_idx].at_flags & flag;
#ifndef PBS_MOM
	case OBJ_NODE:
                return ((pbs_node *)pobj)->nd_attr[attr_idx].at_flags & flag;
#endif

	default:
		break;
	}

	return 0;
}

/**
 * @brief	Getter function for object attribute of type string
 *
 * @param[in]	pobj - pointer to the obj
 * @param[in]	attr_idx - index of the attribute to return
 * @param[in]	obj_type - Type of the object
 *
 * @return	char *
 * @retval	string value of the attribute
 * @retval	NULL if pobj is NULL
 */
char *
__get_attr_str(const void *pobj, int attr_idx, obj_type_t obj_type)
{
	if (!pobj)
		return NULL;

	switch (obj_type) {
	case OBJ_JOB:
		return ((job *)pobj)->ji_wattr[attr_idx].at_val.at_str;
#ifndef PBS_MOM
	case OBJ_NODE:
		return ((pbs_node *)pobj)->nd_attr[attr_idx].at_val.at_str;
#endif

	default:
		break;
	}

	return NULL;
}

/**
 * @brief	Getter function for object attribute of type long
 *
 * @param[in]	pobj - pointer to the obj
 * @param[in]	attr_idx - index of the attribute to return
 * @param[in]	obj_type - Type of the object
 *
 * @return	long
 * @retval	long value of the attribute
 * @retval	-1 if pobj is NULL
 */
long
__get_attr_long(const void *pobj, int attr_idx, obj_type_t obj_type)
{
	if (!pobj)
		return -1;

	switch (obj_type) {
	case OBJ_JOB:
		return ((job *)pobj)->ji_wattr[attr_idx].at_val.at_long;
#ifndef PBS_MOM
	case OBJ_NODE:
		return ((pbs_node *)pobj)->nd_attr[attr_idx].at_val.at_long;
#endif

	default:
		break;
	}

	return -1;
}

/**
 * @brief	Getter function for obj attribute's user_encoded value
 *
 * @param[in]	pobj - pointer to the obj
 * @param[in]	attr_idx - index of the attribute to return
 * @param[in]	obj_type - Type of the object
 *
 * @return	svrattrl *
 * @retval	user_encoded value of the attribute
 * @retval	NULL if pobj is NULL
 */
svrattrl *
__get_attr_usr_encoded(const void *pobj, int attr_idx, obj_type_t obj_type)
{
	if (pobj == NULL)
		return NULL;

	switch (obj_type) {
	case OBJ_JOB:
		return ((job *)pobj)->ji_wattr[attr_idx].at_user_encoded;
#ifndef PBS_MOM
	case OBJ_NODE:
		return ((pbs_node *)pobj)->nd_attr[attr_idx].at_user_encoded;
#endif

	default:
		break;
	}

	return NULL;
}

/**
 * @brief	Getter function for obj attribute's priv_encoded value
 *
 * @param[in]	pobj - pointer to the obj
 * @param[in]	attr_idx - index of the attribute to return
 * @param[in]	obj_type - Type of the object
 *
 * @return	svrattrl *
 * @retval	priv_encoded value of the attribute
 * @retval	NULL if pobj is NULL
 */
svrattrl *
__get_attr_priv_encoded(const void *pobj, int attr_idx, obj_type_t obj_type)
{
	if (!pobj)
		return NULL;

	switch (obj_type) {
	case OBJ_JOB:
		return ((job *)pobj)->ji_wattr[attr_idx].at_priv_encoded;
#ifndef PBS_MOM
	case OBJ_NODE:
		return ((pbs_node *)pobj)->nd_attr[attr_idx].at_priv_encoded;
#endif

	default:
		break;
	}

	return NULL;
}

int
__get_attr_flag(const void *pobj, int attr_idx, obj_type_t obj_type)
{
	if (!pobj)
		return 0;

	switch (obj_type) {

	case OBJ_JOB:
		return ((job *) pobj)->ji_wattr[attr_idx].at_flags;

#ifndef PBS_MOM
	case OBJ_NODE:
		return ((pbs_node *) pobj)->nd_attr[attr_idx].at_flags;
#endif
	default:
		break;
	}

	return 0;
}

/**
 * @brief	Generic obj attribute setter (call if you want at_set() action functions to be called)
 *
 * @param[in]	pobj - pointer to obj
 * @param[in]	attr_idx - attribute index to set
 * @param[in]	val - new val to set
 * @param[in]	rscn - new resource val to set, if applicable
 * @param[in]	op - batch_op operation, SET, INCR, DECR etc.
 * @param[in]	obj_type - Type of the object
 *
 * @return	int
 * @retval	0 for success
 * @retval	1 for failure
 */
int
__set_attr_generic(void *pobj, int attr_idx, char *val, char *rscn, enum batch_op op, obj_type_t obj_type)
{
	if (pobj == NULL || val == NULL)
		return 1;

	switch (obj_type) {

	case OBJ_JOB:
		return set_attr_generic(&((job *) pobj)->ji_wattr[attr_idx], &job_attr_def[attr_idx], val, rscn, op);

#ifndef PBS_MOM
	case OBJ_NODE:
		return set_attr_generic(&((pbs_node *) pobj)->nd_attr[attr_idx], &node_attr_def[attr_idx], val, rscn, op);
#endif

	default:
		break;
	}

	return 1;
}

/**
 * @brief	"fast" obj attribute setter for string values
 *
 * @param[in]	pobj - pointer to obj
 * @param[in]	attr_idx - attribute index to set
 * @param[in]	val - new val to set
 * @param[in]	rscn - new resource val to set, if applicable
 * @param[in]	obj_type - Type of the object
 *
 * @return	int
 * @retval	0 for success
 * @retval	1 for failure
 */
int
__set_attr_str_light(void *pobj, int attr_idx, char *val, char *rscn, obj_type_t obj_type)
{
	if (pobj == NULL || val == NULL)
		return 1;

	switch (obj_type) {

	case OBJ_JOB:
		set_attr_generic(&((job *) pobj)->ji_wattr[attr_idx], &job_attr_def[attr_idx], val, rscn, INTERNAL);
#ifndef PBS_MOM
	case OBJ_NODE:
		set_attr_generic(&((pbs_node *) pobj)->nd_attr[attr_idx], &node_attr_def[attr_idx], val, rscn, INTERNAL);
		break;
#endif
	default:
		break;
	}

	return 1;
}

/**
 * @brief	"fast" obj attribute setter
 *
 * @param[in]	pobj - pointer to obj
 * @param[in]	attr_idx - attribute index to set
 * @param[in]	val - new val to set
 * @param[in]	rscn - new resource val to set, if applicable
 * @param[in]	obj_type - Type of the object
 *
 * @return	int
 * @retval	0 for success
 * @retval	1 for failure
 */
int
__set_attr(void *pobj, int attr_idx, void *val, enum batch_op op, obj_type_t obj_type)
{
	attribute *pattr = NULL;

	if (pobj == NULL)
		return 1;

	switch (obj_type) {

	case OBJ_JOB:
		pattr = &((job *) pobj)->ji_wattr[attr_idx];
		break;
#ifndef PBS_MOM
	case OBJ_NODE:
		pattr = &((pbs_node *) pobj)->nd_attr[attr_idx];
#endif

	default:
		return 1;
	}

	switch (job_attr_def[attr_idx].at_type) {

	case ATR_TYPE_LONG:
		set_attr_l(pattr, *(long *) val, op);
		break;
	case ATR_TYPE_CHAR:
		set_attr_c(pattr, *(char *) val, op);
		break;
	case ATR_TYPE_BOOL:
		set_attr_b(pattr, *(int *) val, op);
		break;

	default:
		break;
	}

	return 0;
}

/**
 * @brief	Free a obj attribute
 *
 * @param[in]	pobj - pointer to obj
 * @param[in]	attr_idx - attribute index to free
 * @param[in]	obj_type - Type of the object
 *
 * @return	void
 */
void
__free_attr(void *pobj, int attr_idx, obj_type_t obj_type)
{
	switch (obj_type) {

	case OBJ_JOB:
		job_attr_def[attr_idx].at_free(&((job *) pobj)->ji_wattr[attr_idx]);
		break;
#ifndef PBS_MOM
	case OBJ_NODE:
		node_attr_def[attr_idx].at_free(&((pbs_node *) pobj)->nd_attr[attr_idx]);
		break;
#endif

	default:
		break;
	}
}
