/*
 * Copyright (C) 1994-2020 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of both the OpenPBS software ("OpenPBS")
 * and the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * OpenPBS is free software. You can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * OpenPBS is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * PBS Pro is commercially licensed software that shares a common core with
 * the OpenPBS software.  For a copy of the commercial license terms and
 * conditions, go to: (http://www.pbspro.com/agreement.html) or contact the
 * Altair Legal Department.
 *
 * Altair's dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of OpenPBS and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair's trademarks, including but not limited to "PBS™",
 * "OpenPBS®", "PBS Professional®", and "PBS Pro™" and Altair's logos is
 * subject to Altair's trademark licensing policies.
 */

#include <pbs_config.h>   /* the master config generated by configure */

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "pbs_ifl.h"
#include "libpbs.h"
#include "attribute.h"
#include "pbs_nodes.h"
#include "pbs_error.h"


/**
 * @brief	Getter function for node attribute of type string
 *
 * @param[in]	pnode - pointer to the node
 * @param[in]	attr_idx - index of the attribute to return
 *
 * @return	char *
 * @retval	string value of the attribute
 * @retval	NULL if pnode is NULL
 */
char *
get_ndattr_str(const pbs_node *pnode, int attr_idx)
{
	if (pnode)
		return pnode->nd_attr[attr_idx].at_val.at_str;

	return NULL;
}

/**
 * @brief	Getter function for node attribute of type long
 *
 * @param[in]	pnode - pointer to the node
 * @param[in]	attr_idx - index of the attribute to return
 *
 * @return	long
 * @retval	long value of the attribute
 * @retval	-1 if pnode is NULL
 */
long
get_ndattr_long(const pbs_node *pnode, int attr_idx)
{
	if (pnode != NULL)
		return pnode->nd_attr[attr_idx].at_val.at_long;

	return -1;
}

/**
 * @brief	Getter function for node attribute's user_encoded value
 *
 * @param[in]	pnode - pointer to the node
 * @param[in]	attr_idx - index of the attribute to return
 *
 * @return	svrattrl *
 * @retval	user_encoded value of the attribute
 * @retval	NULL if pnode is NULL
 */
svrattrl *
get_ndattr_usr_encoded(const pbs_node *pnode, int attr_idx)
{
	if (pnode != NULL)
		return pnode->nd_attr[attr_idx].at_user_encoded;

	return NULL;
}

/**
 * @brief	Getter function for node attribute's priv_encoded value
 *
 * @param[in]	pnode - pointer to the node
 * @param[in]	attr_idx - index of the attribute to return
 *
 * @return	svrattrl *
 * @retval	priv_encoded value of the attribute
 * @retval	NULL if pnode is NULL
 */
svrattrl *
get_ndattr_priv_encoded(const pbs_node *pnode, int attr_idx)
{
	if (pnode)
		return pnode->nd_attr[attr_idx].at_priv_encoded;

	return NULL;
}

int
get_ndattr_flag(const pbs_node *pnode, int attr_idx)
{
	if (pnode)
		return pnode->nd_attr[attr_idx].at_flags;

	return 0;
}

/**
 * @brief	Generic Job attribute setter (call if you want at_set() action functions to be called)
 *
 * @param[in]	pnode - pointer to node
 * @param[in]	attr_idx - attribute index to set
 * @param[in]	val - new val to set
 * @param[in]	rscn - new resource val to set, if applicable
 * @param[in]	op - batch_op operation, SET, INCR, DECR etc.
 *
 * @return	int
 * @retval	0 for success
 * @retval	1 for failure
 */
int
set_ndattr_generic(pbs_node *pnode, int attr_idx, char *val, char *rscn, enum batch_op op)
{
	if (pnode == NULL || val == NULL)
		return 1;

	return set_attr_generic(&pnode->nd_attr[attr_idx], &node_attr_def[attr_idx], val, rscn, op);
}

/**
 * @brief	"fast" node attribute setter for string values
 *
 * @param[in]	pnode - pointer to node
 * @param[in]	attr_idx - attribute index to set
 * @param[in]	val - new val to set
 * @param[in]	rscn - new resource val to set, if applicable
 *
 * @return	int
 * @retval	0 for success
 * @retval	1 for failure
 */
int
set_ndattr_str_light(pbs_node *pnode, int attr_idx, char *val, char *rscn)
{
	if (pnode == NULL || val == NULL)
		return 1;

	return set_attr_generic(&pnode->nd_attr[attr_idx], &node_attr_def[attr_idx], val, rscn, INTERNAL);
}

/**
 * @brief	"fast" node attribute setter
 *
 * @param[in]	pnode - pointer to node
 * @param[in]	attr_idx - attribute index to set
 * @param[in]	val - new val to set
 * @param[in]	rscn - new resource val to set, if applicable
 *
 * @return	int
 * @retval	0 for success
 * @retval	1 for failure
 */
int
set_ndattr_light(pbs_node *pnode, int attr_idx, void *val, enum batch_op op)
{
	attribute *pattr;

	if (pnode == NULL)
		return 1;

	pattr = &pnode->nd_attr[attr_idx];

	switch (node_attr_def[attr_idx].at_type) {

	case ATR_TYPE_LONG:
		set_attr_l(pattr, *(long *) val, op);
		break;
	case ATR_TYPE_CHAR:
		set_attr_c(pattr, *(char *) val, op);
		break;
	case ATR_TYPE_BOOL:
		set_attr_b(pattr, *(int *) val, op);
		break;

	default:
		break;
	}

	return 0;
}

void
reset_ndattr_flag(pbs_node *pnode, int attr_idx, int flag)
{
	if (!pnode)
		return;

	pnode->nd_attr[attr_idx].at_flags = flag;
}

void
set_ndattr_flag(pbs_node *pnode, int attr_idx, int flag)
{
	if (!pnode)
		return;

	pnode->nd_attr[attr_idx].at_flags |= flag;
}

void
unset_ndattr_flag(pbs_node *pnode, int attr_idx, int flag)
{
	if (!pnode)
		return;

	pnode->nd_attr[attr_idx].at_flags &= ~flag;
}

int
is_ndattr_flag_set(const pbs_node *pnode, int attr_idx, int flag)
{
	return get_ndattr_flag(pnode, attr_idx) & flag;
}

/**
 * @brief	Check if a node attribute is set
 *
 * @param[in]	pnode - pointer to node
 * @param[in]	attr_idx - attribute index to check
 *
 * @return	int
 * @retval	1 if it is set
 * @retval	0 otherwise
 */
int
is_ndattr_set(const pbs_node *pnode, int attr_idx)
{
	return is_ndattr_flag_set(pnode, attr_idx, ATR_VFLAG_SET);
}

/**
 * @brief	Mark a node attribute as "set"
 *
 * @param[in]	pnode - pointer to node
 * @param[in]	attr_idx - attribute index to set
 *
 * @return	void
 */
void
mark_ndattr_not_set(pbs_node *pnode, int attr_idx)
{
	unset_ndattr_flag(pnode, attr_idx, ATR_VFLAG_SET);
	set_ndattr_flag(pnode, attr_idx, ATR_MOD_MCACHE);
}

/**
 * @brief	Mark a node attribute as "not set"
 *
 * @param[in]	pnode - pointer to node
 * @param[in]	attr_idx - attribute index to set
 *
 * @return	void
 */
void
mark_ndattr_set(pbs_node *pnode, int attr_idx)
{
	set_ndattr_flag(pnode, attr_idx, ATR_VFLAG_SET);
}

/**
 * @brief	Free a node attribute
 *
 * @param[in]	pnode - pointer to node
 * @param[in]	attr_idx - attribute index to free
 *
 * @return	void
 */
void
free_ndattr(pbs_node *pnode, int attr_idx)
{
	if (pnode)
		node_attr_def[attr_idx].at_free(&pnode->nd_attr[attr_idx]);
}

resource *
get_nd_resc_for_update()
{
	if (pnode)
		
}
